; Ekoparty Badge v1 custom hardware: bare nRF52840, Ra-01SH, SSD1315 OLED,
; 6 decorative SK6812 pixels, 1 pairing-status SK6812, piezo and navigation button.
[env:ekoparty_badge_v1]
extends = nrf52840_base
board = ekoparty_badge_v1
board_level = extra
custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = PRIVATE_HW
custom_meshtastic_architecture = nrf52840
custom_meshtastic_actively_supported = false
custom_meshtastic_display_name = Ekoparty Badge v1
custom_meshtastic_support_level = 3
custom_meshtastic_tags = Ekoparty
custom_meshtastic_requires_dfu = true
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/diy/ekoparty_badge_v1
  -I src/platform/nrf52/softdevice
  -I src/platform/nrf52/softdevice/nrf52
  -DPRIVATE_HW
  -DEKOPARTY_BADGE
  -DEKOPARTY_BADGE_V1
  -DMESHTASTIC_EXCLUDE_GPS=1
  -DMESHTASTIC_ENABLE_POSITION_MODULE=1
  -DHAS_NEOPIXEL
  -DNEOPIXEL_COUNT=6
  -DNEOPIXEL_DATA=13
  -DNEOPIXEL_TYPE="(NEO_GRB + NEO_KHZ800)"
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/diy/ekoparty_badge_v1>
debug_tool = jlink
upload_protocol = jlink
